name: Bash Script Workflow

on:
  push:
    branches:
      - main # Change this to your branch name

jobs:
  run_bash_script:
    runs-on: ubuntu-latest # You can choose the operating system you prefer

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Bash script
        run: |
          bash your_script.sh
