name: Deploy S3,Deploy Lambda Function, LEXV2

on:
  push:
    branches:
      - main  

jobs:
  deploy-s3-lambda:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1  

      - name: Delete S3 Bucket
        run: |
          # Replace your-bucket-name with your actual bucket name
          aws s3 rb s3://vedansh --force  --region us-east-1  # Ignore error if bucket doesn't exist

      - name: Deploy S3 Bucket
        run: |
         aws s3api create-bucket --bucket vedansh --region us-west-1 --create-bucket-configuration LocationConstraint=us-west-1


      - name: Upload Image to S3
        run: |
          aws s3 cp WhiteSaucePasta.jpg s3://vedansh

      # - name: Delete Lambda Function
      #   run: |
      #     aws lambda delete-function --function-name ved --region us-west-1   # Ignore error if function doesn't exist

      - name: Deploy Lambda Function
        run: |
          aws lambda create-function --function-name PastaOrderFunction --runtime python3.8 --role arn:aws:iam::115941228118:role/service-role/PastaOrderFunction-role-kf02fxax --handler lambda_function.lambda_handler --zip-file fileb://PastaOrderFunction-195f7a38-883c-43a0-a8f3-007559e8df72.zip --region ap-northeast-3 || True

      - name: Export and Store Lex Bot as Artifact
        run: |
          export_response=$(aws lexv2-models create-export --resource-specification "{\"botExportSpecification\": {\"botId\": \"ANSUSIV0FR\", \"botVersion\": \"1\"}}" --file-format LexJson --region us-east-1)
          export_id=$(echo "$export_response" | jq -r '.exportId')
          echo "$export_id"
          echo "-----"
          sleep 20

          data=$(aws lexv2-models describe-export --export-id $export_id --region us-east-1)
          download_url=$(echo "$data" | jq -r '.downloadUrl')
          echo "Export Response JSON: $data"
          wget -O exported_bot.zip "$download_url"

      - name: Save Exported Bot as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: exported-lex-bot
          path: exported_bot.zip

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
            python-version: 3.8  
  
      - name: Install dependencies
        run: |
          pip install urllib3
  
      - name: Upload Bot
        run: |
          import=$(aws lexv2-models create-upload-url --region us-east-1)
          sleep 30
          upload_Url=$(echo "$import" | jq -r '.uploadUrl')
          import_id=$(echo "$import" | jq -r '.importId')
          echo "Upload URL: $upload_Url"
          echo "::set-output name=file_data::$file_data"
          curl -X PUT -H "Content-Type: application/zip" --data-binary "@exported_bot.zip" "$upload_Url"
          # import bot to lexv2
          aws lexv2-models start-import --import-id "$import_id" --resource-specification "{\"botImportSpecification\": {\"botName\": \"vedanshBot\",\"roleArn\": \"arn:aws:iam::115941228118:role/aws-servicerole/lexv2.amazonaws.com/AWSServiceRoleForLexV2Bots_ECVNQFI8F8M\",\"dataPrivacy\": {\"childDirected\": false},\"idleSessionTTLInSeconds\": 600}}" --merge-strategy "FailOnConflict" --region us-east-1
          sleep 40
          aws lexv2-models describe-import --import-id "$import_id" --region us-east-1
      